
title = 'Dynamic Simulation Environment'
baseURL = 'https://boschglobal.github.io/dse.doc/'


# Hugo base configuration
# =======================

# Language settings
contentDir = "content"
defaultContentLanguage = "en"

# Will give values to .Lastmod etc.
enableGitInfo = true

[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyCloud = []
taxonomyCloudTitle = ["Tag Cloud", "Categories"]
taxonomyPageHeader = ["tags", "categories"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "tango"


# Docsy configuration
# ===================

[params]
copyright = "Robert Bosch GmbH"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://boschglobal.github.com/dse.doc/"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/boschglobal/dse.doc"
github_project_repo = "https://github.com/boschglobal?q=dse&type=all"
github_branch = "main"

# Enable Algolia DocSearch
# search.algolia = false
# Enable Lunr.js offline search
offlineSearch = true

# User interface configuration
[params.ui]
breadcrumb_disable = false
footer_about_disable = true
navbar_logo = true
navbar_translucent_over_cover_disable = true

# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
sidebar_menu_foldable = true
sidebar_cache_limit = 100
sidebar_search_disable = false

[params.ui.feedback]
enable = false

[params.ui.readingtime]
enable = false

[params.links]
[[params.links.user]]
  name = "GitHub Discussions"
  url = "https://github.com/boschglobal/dse.modelc/discussions"
  icon = "fab fa-github"
  desc = "GitHub Discussions"
[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/boschglobal?q=dse&type=all"
  icon = "fab fa-github"
  desc = "Contribute to DSE here!"


# Hugo module configuration
# =========================

[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    min = "0.73.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false


# External Documentation Mounts
# =============================

# DSE CLib
# --------
[[module.imports]]
  path = "github.com/boschglobal/dse.clib"
  disable = false
  ignoreConfig = true
  [[module.imports.mounts]]
    source = "doc/content/apis"
    target = "content/apis"
  [[module.imports.mounts]]
    source = "doc/content/docs"
    target = "content/docs"


# DSE ModelC
# -----------
[[module.imports]]
  path = "github.com/boschglobal/dse.modelc"
  disable = false
  ignoreConfig = true
  [[module.imports.mounts]]
    source = "doc/content/apis"
    target = "content/apis"
  [[module.imports.mounts]]
    source = "doc/content/docs"
    target = "content/docs"


# DSE FMI
# -------
[[module.imports]]
  path = "github.com/boschglobal/dse.fmi"
  disable = false
  ignoreConfig = true
  [[module.imports.mounts]]
    source = "doc/content/apis"
    target = "content/apis"
  [[module.imports.mounts]]
    source = "doc/content/docs"
    target = "content/docs"


# DSE Network
# -----------
[[module.imports]]
  path = "github.com/boschglobal/dse.network"
  disable = false
  ignoreConfig = true
  [[module.imports.mounts]]
    source = "doc/content/apis"
    target = "content/apis"
  [[module.imports.mounts]]
    source = "doc/content/docs"
    target = "content/docs"


# DSE Schemas
# -----------
[[module.imports]]
  path = "github.com/boschglobal/dse.schemas"
  disable = false
  ignoreConfig = true
  [[module.imports.mounts]]
    source = "doc/content/schemas"
    target = "content/schemas"


# DSE Standards - DSE/NCodec
# --------------------------
[[module.imports]]
  path = "github.com/boschglobal/dse.standards"
  disable = false
  ignoreConfig = true
  [[module.imports.mounts]]
    source = "doc/content/apis"
    target = "content/apis"
