name: Public HTML

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: [main, devel]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [main, devel]
#  schedule:
#    - cron: '0 6,12,16 * * *'
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    container:
      image: ghcr.io/boschglobal/dse-docsy-builder:main
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        env:
          HUGO_SECURITY_EXEC_OSENV: ".*"
        run: |
          hugo mod get -u
          hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: public_html
